#!/usr/bin/python

import os
import sys

from optparse import OptionParser
from checkbox.lib.fifo import FifoReader, FifoWriter

from checkbox.job import Job, FAIL


def main(args):
    usage = "Usage: %prog INPUT OUTPUT"
    parser = OptionParser(usage=usage)
    parser.add_option("-p", "--path",
        help="PATH variable to replace in the environment")
    (options, args) = parser.parse_args(args)

    if len(args) < 2:
        parser.error("Missing INPUT and OUTPUT")

    if options.path:
        os.environ["PATH"] = options.path

    reader = FifoReader(args[0])
    writer = FifoWriter(args[1])

    while True:
        try:
            message = reader.read_object()
            if isinstance(message, dict) and "command" in message:
                job = Job(message["command"], message.get("environ"),
                    message.get("timeout"))
                result = job.execute()
            else:
                result = (FAIL, "", 0,)

            writer.write_object(result)
        except IOError, e:
            break

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
