#!/usr/bin/env python
#
# This file is part of Checkbox.
#
# Copyright 2008 Canonical Ltd.
#
# Checkbox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Checkbox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Checkbox.  If not, see <http://www.gnu.org/licenses/>.
#
import sys
import posixpath


# Workaround for python-support on older systems
directory = "/usr/share/python-support"
for package in ["checkbox", "checkbox-cli", "checkbox-gtk"]:
    sys.path.append(posixpath.join(directory, package))


from checkbox.application import ApplicationManager


def main():
    manager = ApplicationManager()
    application = manager.create_application(sys.argv)
    application.run()


if __name__ == "__main__":
    main()
