#!/usr/bin/env python

import os
import sys


# Workaround for python-support on older systems
directory = "/usr/share/python-support"
for package in ["hwtest", "hwtest-cli", "hwtest-gtk"]:
    sys.path.append(os.path.join(directory, package))


from hwtest.application import ApplicationManager


def main():
    manager = ApplicationManager()
    application = manager.create_application(sys.argv)
    application.run()


if __name__ == "__main__":
    main()
