#!/bin/sh
# This script is invoked by tarmac - the automatic branch lader - before it
# allows a merge request to land into trunk
set -x -e
./test
# ZK: disabled as bzr crashes when invoked from tarmac
# ./lint
