#!/bin/bash

if [[ -z `which autopilot` ]]; then
  echo "Autopilot is not installed. Skip"
  exit 1
fi

SCRIPTPATH=`dirname $0`
pushd ${SCRIPTPATH}
autopilot run --timeout-profile=long checkbox_touch
ret=$?
popd
exit $ret

