#!/usr/bin/env python3
# this file is part of checkbox.
#
# copyright 2014 canonical ltd.
# written by:
#   maciej kisielewski <maciej.kisielewski@canonical.com>
#
# checkbox is free software: you can redistribute it and/or modify
# it under the terms of the gnu general public license version 3,
# as published by the free software foundation.
#
# checkbox is distributed in the hope that it will be useful,
# but without any warranty; without even the implied warranty of
# merchantability or fitness for a particular purpose.  see the
# gnu general public license for more details.
#
# you should have received a copy of the gnu general public license
# along with checkbox.  if not, see <http://www.gnu.org/licenses/>.
"""
Download and extract .deb packages necessary to run checkbox-touch
Extraction is done to specific directories as required by click package

For typical development iteration, after hacking something in plainbox,
run ./get-libs --plainbox-only
"""

import argparse
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request

from utils import get_package_from_url_and_extract
from utils import prepare_uris
from utils import rsync_tree


def extract_plainbox(src_tarball, version):
    with tempfile.TemporaryDirectory() as tmp:
        tarball = tarfile.open(src_tarball)
        members = [member for member in tarball.getmembers()
                   if member.name.startswith(
                       "plainbox-{}/plainbox/".format(version)) or
                   member.name.startswith(
                       "plainbox-{}/plainbox.egg-info".format(version))]
        tarball.extractall(tmp, members=members)
        rsync_tree(
            os.path.join(tmp, "plainbox-{}".format(version), "plainbox"),
            os.path.join('lib', 'py', 'plainbox'),
            preserve_symlinks=1)
        # copy plainbox.egg
        rsync_tree(
            os.path.join(tmp, "plainbox-{}".format(version),
                         'plainbox.egg-info'),
            os.path.join('lib', 'py', 'plainbox.egg-info'),
            preserve_symlinks=1)


def get_plainbox_from_pypi(version='0.22.2'):
    # plaibox_pypi contains URL from which to download plainbox
    plainbox_pypi = ('https://pypi.python.org/packages/source'
                     '/p/plainbox/plainbox-{}.tar.gz'.format(version))
    with tempfile.TemporaryDirectory() as tmp:
        filename = os.path.join(tmp, plainbox_pypi.split('/')[-1])
        print('retrieving {0}'.format(plainbox_pypi))
        urllib.request.urlretrieve(plainbox_pypi, filename)
        extract_plainbox(filename, version)


def get_local_plainbox():
    # TODO: user shouldn't specify version of local plainbox
    plainbox_setup_path = os.path.join(os.getcwd(), '..', 'plainbox',
                                       'setup.py')
    plainbox_version = subprocess.check_output([plainbox_setup_path,
        '--version']).decode(sys.stdout.encoding).strip()

    plainbox_setup_dir = os.path.split(plainbox_setup_path)[0]
    print('building local plainbox')
    ret = subprocess.check_call([plainbox_setup_path, '-q', 'sdist'],
                                cwd=plainbox_setup_dir)
    if ret != 0:
        raise Exception(
            "Could not build plainbox using {}. Check above output"
            .format(plainbox_setup_path))
    filename = os.path.join(plainbox_setup_dir, 'dist', 'plainbox-{}.tar.gz'
                            .format(plainbox_version))
    extract_plainbox(filename, plainbox_version)


def main():
    parser = argparse.ArgumentParser("Get necessary libs for checkbox-touch")
    parser.add_argument("--get-pypi-plainbox",
                        action='store_true',
                        help="Use plainbox downloaded from pypi")
    parser.add_argument("--plainbox-only", action='store_true',
                        help="Get plainbox only")
    parser.add_argument("--get-autopilot",
                        action='store_true',
                        help="Download libs for autopilot")
    args = parser.parse_args()
    if args.get_pypi_plainbox:
        get_plainbox_from_pypi()
    else:
        get_local_plainbox()
    if args.plainbox_only:
        # skip downloading rest of the libs
        return
    packages = [
        'libpython3.5', 'pyotherside', 'python3-xlsxwriter',
        'python3-jinja2', 'python3-markupsafe', 'python3-padme',
        'python3-requests', 'python3-urllib3', 'python3-guacamole',
        'python3-requests-oauthlib']
    # additional packages needed to support autopilot tests.  these were obtained by
    # running apt-cache depends on python3-autopilot
    if args.get_autopilot:
        packages += [
            'python3-autopilot', 'python3-psutil', 'python3-testtools',
            'python3-pil', 'libjs-jquery', 'libjs-underscore', 'libwebp5',
            'libwebpmux1', 'python3-decorator', 'python3-testscenarios',
            'python3-subunit', 'python3-fixtures', 'python3-junitxml',
            'python3-extras', 'python3-evdev']
    uris = prepare_uris(packages)
    # libs_urls contains list of .deb packages that will be downloaded and
    # extracted. After extraction contents of ./usr/lib are copied to ./lib
    for lib in uris:
        with tempfile.TemporaryDirectory() as tmp:
            get_package_from_url_and_extract(uris[lib], tmp)
            # TODO: remove unwanted files from the extracted tree (e.g. *.h)
            rsync_tree(
                os.path.join(tmp, 'usr', 'lib'), 'lib',
                preserve_symlinks=1)
    # python3_libs_urls contains list of .deb packages that will be downloaded
    # and extracted. After extraction contents of
    # ./usr/lib/python3/dist-packages are copied to ./lib/py.
    python3_libs = ['python3-xlsxwriter', 'python3-jinja2',
                    'python3-markupsafe', 'python3-padme', 'python3-requests',
                    'python3-urllib3', 'python3-guacamole',
                    'python3-requests-oauthlib']

    # additional libs needed to support autopilot tests.  these were obtained by
    # running apt-cache depends on python3-autopilot
    python3_ap_libs = ['python3-autopilot', 'python3-psutil',
                       'python3-pil', 'python3-decorator', 'python3-testtools',
                       'python3-subunit', 'python3-testscenarios', 'python3-junitxml', 'python3-fixtures',
                       'python3-extras', 'python3-evdev']
    if args.get_autopilot:
        python3_libs += python3_ap_libs
    for pylib in [uris[lib] for lib in python3_libs]:
        with tempfile.TemporaryDirectory() as tmp:
            get_package_from_url_and_extract(pylib, tmp)
            rsync_tree(
                os.path.join(tmp, 'usr', 'lib', 'python3',
                             'dist-packages'),
                os.path.join('lib', 'py'),
                preserve_symlinks=1)
    with tempfile.TemporaryDirectory() as tmp:
        get_package_from_url_and_extract(uris['pyotherside'], tmp)
        src = os.path.join(
            tmp, 'usr', 'lib', 'arm-linux-gnueabihf', 'qt5', 'qml')
        dest = os.path.join('lib', 'arm-linux-gnueabihf')
        if os.path.exists(src) and os.path.isdir(src):
            rsync_tree(src, dest, preserve_symlinks=1)

    # Remove the python3.4 directory
    # currently it only holds a few config-directories with symlinks
    # and those are not used by anything from this location
    if os.path.exists('lib/python3.4'):
        shutil.rmtree('lib/python3.4')


if __name__ == "__main__":
    main()
