# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/checkbox-qt.ui'
#
# Created: Fri Dec  9 12:39:19 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(452, 400)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(450, 400))
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "System Testing", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/22x22/apps/checkbox.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.top = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top.sizePolicy().hasHeightForWidth())
        self.top.setSizePolicy(sizePolicy)
        self.top.setMinimumSize(QtCore.QSize(450, 69))
        self.top.setObjectName(_fromUtf8("top"))
        self.bannerLabel = QtGui.QLabel(self.top)
        self.bannerLabel.setGeometry(QtCore.QRect(83, 45, 141, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bannerLabel.sizePolicy().hasHeightForWidth())
        self.bannerLabel.setSizePolicy(sizePolicy)
        self.bannerLabel.setText(QtGui.QApplication.translate("Form", "System Testing", None, QtGui.QApplication.UnicodeUTF8))
        self.bannerLabel.setObjectName(_fromUtf8("bannerLabel"))
        self.verticalLayout.addWidget(self.top)
        self.center = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.center.sizePolicy().hasHeightForWidth())
        self.center.setSizePolicy(sizePolicy)
        self.center.setMinimumSize(QtCore.QSize(450, 0))
        self.center.setObjectName(_fromUtf8("center"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.center)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self._notebook = QtGui.QTabWidget(self.center)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._notebook.sizePolicy().hasHeightForWidth())
        self._notebook.setSizePolicy(sizePolicy)
        self._notebook.setMinimumSize(QtCore.QSize(0, 0))
        self._notebook.setTabShape(QtGui.QTabWidget.Rounded)
        self._notebook.setObjectName(_fromUtf8("_notebook"))
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setMinimumSize(QtCore.QSize(441, 0))
        self.tab.setMaximumSize(QtCore.QSize(441, 16777215))
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.infoWindow = QtGui.QPlainTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoWindow.sizePolicy().hasHeightForWidth())
        self.infoWindow.setSizePolicy(sizePolicy)
        self.infoWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.infoWindow.setReadOnly(True)
        self.infoWindow.setObjectName(_fromUtf8("infoWindow"))
        self.horizontalLayout_2.addWidget(self.infoWindow)
        self._notebook.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.treeInfo = QtGui.QPlainTextEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeInfo.sizePolicy().hasHeightForWidth())
        self.treeInfo.setSizePolicy(sizePolicy)
        self.treeInfo.setMinimumSize(QtCore.QSize(0, 0))
        self.treeInfo.setMaximumSize(QtCore.QSize(450, 38))
        self.treeInfo.setReadOnly(True)
        self.treeInfo.setObjectName(_fromUtf8("treeInfo"))
        self.verticalLayout_6.addWidget(self.treeInfo)
        self.treeView = QtGui.QTreeView(self.tab_2)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout_6.addWidget(self.treeView)
        self._notebook.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self._notebook.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self._notebook.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self._notebook)
        self.progressWidget = QtGui.QWidget(self.center)
        self.progressWidget.setObjectName(_fromUtf8("progressWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.progressWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.progressLabel = QtGui.QLabel(self.progressWidget)
        self.progressLabel.setText(_fromUtf8(""))
        self.progressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressLabel.setObjectName(_fromUtf8("progressLabel"))
        self.verticalLayout_5.addWidget(self.progressLabel)
        self.progressBar = QtGui.QProgressBar(self.progressWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_5.addWidget(self.progressBar)
        self.verticalLayout_4.addWidget(self.progressWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.center)
        self.bottom = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom.sizePolicy().hasHeightForWidth())
        self.bottom.setSizePolicy(sizePolicy)
        self.bottom.setMinimumSize(QtCore.QSize(450, 36))
        self.bottom.setObjectName(_fromUtf8("bottom"))
        self.button_next = QtGui.QPushButton(self.bottom)
        self.button_next.setGeometry(QtCore.QRect(360, 6, 81, 29))
        self.button_next.setText(QtGui.QApplication.translate("Form", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.button_next.setObjectName(_fromUtf8("button_next"))
        self.button_previous = QtGui.QPushButton(self.bottom)
        self.button_previous.setGeometry(QtCore.QRect(270, 6, 81, 29))
        self.button_previous.setText(QtGui.QApplication.translate("Form", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.button_previous.setObjectName(_fromUtf8("button_previous"))
        self.button_select_all = QtGui.QPushButton(self.bottom)
        self.button_select_all.setGeometry(QtCore.QRect(177, 5, 81, 30))
        self.button_select_all.setText(QtGui.QApplication.translate("Form", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.button_select_all.setObjectName(_fromUtf8("button_select_all"))
        self.button_deselect_all = QtGui.QPushButton(self.bottom)
        self.button_deselect_all.setGeometry(QtCore.QRect(82, 5, 81, 30))
        self.button_deselect_all.setText(QtGui.QApplication.translate("Form", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.button_deselect_all.setObjectName(_fromUtf8("button_deselect_all"))
        self.verticalLayout.addWidget(self.bottom)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self._notebook.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self._notebook, self.button_next)
        Form.setTabOrder(self.button_next, self.button_previous)

    def retranslateUi(self, Form):
        self._notebook.setTabText(self._notebook.indexOf(self.tab), QtGui.QApplication.translate("Form", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self._notebook.setTabText(self._notebook.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self._notebook.setTabText(self._notebook.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self._notebook.setTabText(self._notebook.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "Page", None, QtGui.QApplication.UnicodeUTF8))

