# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/checkbox-qt.ui'
#
# Created: Fri Jan 20 15:40:37 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName(_fromUtf8("main"))
        main.resize(640, 443)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(main)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(main)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWelcome = QtGui.QWidget()
        self.tabWelcome.setObjectName(_fromUtf8("tabWelcome"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabWelcome)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.welcomeTop = QtGui.QWidget(self.tabWelcome)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcomeTop.sizePolicy().hasHeightForWidth())
        self.welcomeTop.setSizePolicy(sizePolicy)
        self.welcomeTop.setMinimumSize(QtCore.QSize(0, 100))
        self.welcomeTop.setObjectName(_fromUtf8("welcomeTop"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.welcomeTop)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.welcomeTopImage = QtGui.QWidget(self.welcomeTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcomeTopImage.sizePolicy().hasHeightForWidth())
        self.welcomeTopImage.setSizePolicy(sizePolicy)
        self.welcomeTopImage.setMinimumSize(QtCore.QSize(120, 0))
        self.welcomeTopImage.setObjectName(_fromUtf8("welcomeTopImage"))
        self.horizontalLayout_4.addWidget(self.welcomeTopImage)
        self.welcomeTopText = QtGui.QWidget(self.welcomeTop)
        self.welcomeTopText.setObjectName(_fromUtf8("welcomeTopText"))
        self.welcomeLabel = QtGui.QLabel(self.welcomeTopText)
        self.welcomeLabel.setGeometry(QtCore.QRect(30, 20, 330, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(21)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setObjectName(_fromUtf8("welcomeLabel"))
        self.horizontalLayout_4.addWidget(self.welcomeTopText)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.welcomeTop)
        self.welcomeBottom = QtGui.QWidget(self.tabWelcome)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcomeBottom.sizePolicy().hasHeightForWidth())
        self.welcomeBottom.setSizePolicy(sizePolicy)
        self.welcomeBottom.setMinimumSize(QtCore.QSize(0, 0))
        self.welcomeBottom.setObjectName(_fromUtf8("welcomeBottom"))
        self.welcomeTextBox = QtGui.QTextEdit(self.welcomeBottom)
        self.welcomeTextBox.setGeometry(QtCore.QRect(30, 40, 571, 181))
        self.welcomeTextBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.welcomeTextBox.setFrameShadow(QtGui.QFrame.Plain)
        self.welcomeTextBox.setReadOnly(True)
        self.welcomeTextBox.setObjectName(_fromUtf8("welcomeTextBox"))
        self.friendlyTestsButton = QtGui.QPushButton(self.welcomeBottom)
        self.friendlyTestsButton.setGeometry(QtCore.QRect(30, 230, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.friendlyTestsButton.setFont(font)
        self.friendlyTestsButton.setObjectName(_fromUtf8("friendlyTestsButton"))
        self.checkBox = QtGui.QCheckBox(self.welcomeBottom)
        self.checkBox.setGeometry(QtCore.QRect(330, 280, 281, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_5.addWidget(self.welcomeBottom)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tabWelcome, _fromUtf8(""))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tabMain)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.mainTop = QtGui.QWidget(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTop.sizePolicy().hasHeightForWidth())
        self.mainTop.setSizePolicy(sizePolicy)
        self.mainTop.setMinimumSize(QtCore.QSize(0, 89))
        self.mainTop.setStyleSheet(_fromUtf8("background-color: #C2C7CB;"))
        self.mainTop.setObjectName(_fromUtf8("mainTop"))
        self.progressBar = QtGui.QProgressBar(self.mainTop)
        self.progressBar.setGeometry(QtCore.QRect(50, 40, 191, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet(_fromUtf8(" QProgressBar {\n"
"     border: 0px solid grey;\n"
"     border-radius: 0px;\n"
"     background: #FFFFFF;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: #ed7341;\n"
"     width: 20px;\n"
" }"))
        self.progressBar.setProperty("value", 50)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat(_fromUtf8(""))
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.progressLabel = QtGui.QLabel(self.mainTop)
        self.progressLabel.setGeometry(QtCore.QRect(50, 20, 241, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(9)
        self.progressLabel.setFont(font)
        self.progressLabel.setObjectName(_fromUtf8("progressLabel"))
        self.verticalLayout_7.addWidget(self.mainTop)
        self.testsTab = QtGui.QTabWidget(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testsTab.sizePolicy().hasHeightForWidth())
        self.testsTab.setSizePolicy(sizePolicy)
        self.testsTab.setMinimumSize(QtCore.QSize(0, 0))
        self.testsTab.setStyleSheet(_fromUtf8(" QTabWidget::pane#testsTab { /* The tab widget frame */\n"
"     border-top: 10 solid #C2C7CB;\n"
"     position: absolute;\n"
"     top: -1.2em;\n"
" }\n"
"\n"
"QTabWidget::tab-bar#testsTab {\n"
"     alignment: center;\n"
" }\n"
"\n"
" /* Style the tab using the tab sub-control. Note that\n"
"     it reads QTabBar _not_ QTabWidget */\n"
" QTabBar::tab {\n"
"    background: #FFFFFF;\n"
"     border: 1px solid #000000;\n"
"     border-bottom-color: #000000; /* same as the pane color */\n"
"     min-width: 8ex;\n"
"     padding: 0px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"    background: #C2C7CB;\n"
"     border-color: #000000;\n"
"     border-bottom-color: #000000; /* same as pane color */\n"
" }"))
        self.testsTab.setObjectName(_fromUtf8("testsTab"))
        self.welcome = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(11)
        self.welcome.setFont(font)
        self.welcome.setObjectName(_fromUtf8("welcome"))
        self.testsTab.addTab(self.welcome, _fromUtf8(""))
        self.testSelection = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(11)
        self.testSelection.setFont(font)
        self.testSelection.setObjectName(_fromUtf8("testSelection"))
        self.label = QtGui.QLabel(self.testSelection)
        self.label.setGeometry(QtCore.QRect(50, 20, 401, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.line = QtGui.QFrame(self.testSelection)
        self.line.setGeometry(QtCore.QRect(40, 60, 571, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.testSelection)
        self.line_2.setGeometry(QtCore.QRect(410, 40, 20, 211))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_2 = QtGui.QLabel(self.testSelection)
        self.label_2.setGeometry(QtCore.QRect(40, 48, 101, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.testSelection)
        self.label_3.setGeometry(QtCore.QRect(470, 46, 67, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.listView = QtGui.QListView(self.testSelection)
        self.listView.setGeometry(QtCore.QRect(430, 80, 181, 171))
        self.listView.setFrameShape(QtGui.QFrame.NoFrame)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.treeView = QtGui.QTreeView(self.testSelection)
        self.treeView.setGeometry(QtCore.QRect(50, 80, 351, 171))
        self.treeView.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeView.setProperty("showDropIndicator", False)
        self.treeView.setAllColumnsShowFocus(False)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.treeView.header().setVisible(False)
        self.buttonStartTesting = QtGui.QPushButton(self.testSelection)
        self.buttonStartTesting.setGeometry(QtCore.QRect(430, 260, 181, 27))
        self.buttonStartTesting.setObjectName(_fromUtf8("buttonStartTesting"))
        self.testsTab.addTab(self.testSelection, _fromUtf8(""))
        self.testing = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(11)
        self.testing.setFont(font)
        self.testing.setObjectName(_fromUtf8("testing"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.testing)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioTestTab = QtGui.QTabWidget(self.testing)
        self.radioTestTab.setObjectName(_fromUtf8("radioTestTab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_2 = QtGui.QWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 56))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.testTypeLabel = QtGui.QLabel(self.widget_2)
        self.testTypeLabel.setGeometry(QtCore.QRect(20, 10, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(17)
        self.testTypeLabel.setFont(font)
        self.testTypeLabel.setObjectName(_fromUtf8("testTypeLabel"))
        self.purposeLabel = QtGui.QLabel(self.widget_2)
        self.purposeLabel.setGeometry(QtCore.QRect(30, 40, 571, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.purposeLabel.setFont(font)
        self.purposeLabel.setObjectName(_fromUtf8("purposeLabel"))
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.tab)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.widget_5 = QtGui.QWidget(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.scrollArea = QtGui.QScrollArea(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 85, 178))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.stepsFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepsFrame.sizePolicy().hasHeightForWidth())
        self.stepsFrame.setSizePolicy(sizePolicy)
        self.stepsFrame.setMinimumSize(QtCore.QSize(0, 178))
        self.stepsFrame.setSizeIncrement(QtCore.QSize(0, 0))
        self.stepsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.stepsFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.stepsFrame.setLineWidth(0)
        self.stepsFrame.setObjectName(_fromUtf8("stepsFrame"))
        self.verticalLayout_9.addWidget(self.stepsFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_8.addWidget(self.scrollArea)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.widget_4 = QtGui.QWidget(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(150, 0))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.testTestButton = QtGui.QPushButton(self.widget_4)
        self.testTestButton.setGeometry(QtCore.QRect(30, 70, 80, 25))
        self.testTestButton.setObjectName(_fromUtf8("testTestButton"))
        self.yesTestButton = QtGui.QPushButton(self.widget_4)
        self.yesTestButton.setGeometry(QtCore.QRect(30, 110, 80, 25))
        self.yesTestButton.setObjectName(_fromUtf8("yesTestButton"))
        self.noTestButton = QtGui.QPushButton(self.widget_4)
        self.noTestButton.setGeometry(QtCore.QRect(30, 150, 80, 25))
        self.noTestButton.setObjectName(_fromUtf8("noTestButton"))
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.radioTestTab.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.radioTestTab.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.radioTestTab)
        self.widget = QtGui.QWidget(self.testing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 46))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.nextTestButton = QtGui.QPushButton(self.widget)
        self.nextTestButton.setGeometry(QtCore.QRect(520, 10, 80, 25))
        self.nextTestButton.setObjectName(_fromUtf8("nextTestButton"))
        self.previousTestButton = QtGui.QPushButton(self.widget)
        self.previousTestButton.setGeometry(QtCore.QRect(420, 10, 80, 25))
        self.previousTestButton.setObjectName(_fromUtf8("previousTestButton"))
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.testsTab.addTab(self.testing, _fromUtf8(""))
        self.submitResults = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(11)
        self.submitResults.setFont(font)
        self.submitResults.setObjectName(_fromUtf8("submitResults"))
        self.label_4 = QtGui.QLabel(self.submitResults)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.buttonReviewResults = QtGui.QPushButton(self.submitResults)
        self.buttonReviewResults.setGeometry(QtCore.QRect(90, 80, 461, 27))
        self.buttonReviewResults.setObjectName(_fromUtf8("buttonReviewResults"))
        self.buttonSubmitAnounymously = QtGui.QPushButton(self.submitResults)
        self.buttonSubmitAnounymously.setGeometry(QtCore.QRect(90, 120, 461, 27))
        self.buttonSubmitAnounymously.setObjectName(_fromUtf8("buttonSubmitAnounymously"))
        self.groupBox = QtGui.QGroupBox(self.submitResults)
        self.groupBox.setGeometry(QtCore.QRect(90, 180, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEditLaunchpad = QtGui.QLineEdit(self.groupBox)
        self.lineEditLaunchpad.setGeometry(QtCore.QRect(110, 24, 201, 27))
        self.lineEditLaunchpad.setText(_fromUtf8(""))
        self.lineEditLaunchpad.setObjectName(_fromUtf8("lineEditLaunchpad"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.buttonSubmit = QtGui.QPushButton(self.groupBox)
        self.buttonSubmit.setGeometry(QtCore.QRect(320, 24, 101, 27))
        self.buttonSubmit.setObjectName(_fromUtf8("buttonSubmit"))
        self.testsTab.addTab(self.submitResults, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.testsTab)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(main)
        self.tabWidget.setCurrentIndex(0)
        self.testsTab.setCurrentIndex(1)
        self.radioTestTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        main.setWindowTitle(QtGui.QApplication.translate("main", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.welcomeLabel.setText(QtGui.QApplication.translate("main", "Ubuntu System Testing", None, QtGui.QApplication.UnicodeUTF8))
        self.friendlyTestsButton.setText(QtGui.QApplication.translate("main", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("main", "Don\'t show me this message in the future", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWelcome), QtGui.QApplication.translate("main", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.progressLabel.setText(QtGui.QApplication.translate("main", "10 tests completed out of 30 (30%)", None, QtGui.QApplication.UnicodeUTF8))
        self.testsTab.setTabText(self.testsTab.indexOf(self.welcome), QtGui.QApplication.translate("main", " Welcome ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("main", "Lists of tests to run based on your system:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("main", "Components", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("main", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonStartTesting.setText(QtGui.QApplication.translate("main", "Start testing", None, QtGui.QApplication.UnicodeUTF8))
        self.testsTab.setTabText(self.testsTab.indexOf(self.testSelection), QtGui.QApplication.translate("main", " Selection ", None, QtGui.QApplication.UnicodeUTF8))
        self.testTypeLabel.setText(QtGui.QApplication.translate("main", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.purposeLabel.setText(QtGui.QApplication.translate("main", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.testTestButton.setText(QtGui.QApplication.translate("main", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.yesTestButton.setText(QtGui.QApplication.translate("main", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.noTestButton.setText(QtGui.QApplication.translate("main", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTestTab.setTabText(self.radioTestTab.indexOf(self.tab), QtGui.QApplication.translate("main", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTestTab.setTabText(self.radioTestTab.indexOf(self.tab_2), QtGui.QApplication.translate("main", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.nextTestButton.setText(QtGui.QApplication.translate("main", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.previousTestButton.setText(QtGui.QApplication.translate("main", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.testsTab.setTabText(self.testsTab.indexOf(self.testing), QtGui.QApplication.translate("main", " Run ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">Warning: Not all tests have been run yet.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">You can send the results now, but the submission won\'t make it to Ubuntu Friendly.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonReviewResults.setText(QtGui.QApplication.translate("main", "Review Results", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSubmitAnounymously.setText(QtGui.QApplication.translate("main", "Submit Anounymously", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("main", "Submit To Your Launchpad Account", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("main", "Launchpad ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSubmit.setText(QtGui.QApplication.translate("main", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.testsTab.setTabText(self.testsTab.indexOf(self.submitResults), QtGui.QApplication.translate("main", " Results ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), QtGui.QApplication.translate("main", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))

