#!/usr/bin/env python

import os
import sys

from hwtest.application import ApplicationManager
from hwtest.constants import HWTEST_DIR


def main():
    manager = ApplicationManager()
    application = manager.create_application(sys.argv)
    application.plugin_manager.load_directory(os.path.join(HWTEST_DIR, 'plugins'))
    application.plugin_manager.load_directory(os.path.join(HWTEST_DIR, 'gtk', 'plugins'))
    application.run()


if __name__ == "__main__":
    main()
