README /usr/share/doc/checkbox
debian/tmp/usr/share/icons
debian/tmp/usr/share/locale
debian/tmp/usr/share/checkbox/backend
debian/tmp/usr/share/checkbox/run
debian/tmp/usr/share/checkbox/configs
debian/tmp/usr/share/checkbox/data/*
debian/tmp/usr/share/checkbox/install/*
debian/tmp/usr/share/checkbox/jobs/*
debian/tmp/usr/share/checkbox/patches/*
debian/tmp/usr/share/checkbox/plugins/*
debian/tmp/usr/share/checkbox/report/*
debian/tmp/usr/share/checkbox/scripts/*
debian/tmp/usr/share/checkbox/examples/checkbox.ini
debian/tmp/usr/lib/python*/*-packages/checkbox/*
debian/tmp/usr/share/apport/package-hooks/source_checkbox.py
debian/tmp/usr/share/apport/general-hooks/checkbox.py
