#!/bin/sh

# Ubuntu-touch will not be available on 12.04, yet whole checkbox stack is tested against 12.04
# Should 12.04 be detected, skip the tests of checkbox-touch app
if grep 12.04 /etc/lsb-release; then echo "WARNING NOT TESTING UNSUPPORTED RELEASE"; exit 0; fi

# Run checkbox-touch with fake X
# xvfb-run --server-args='-screen 0 1024x768x24 -ac +extension GLX +render -noreset' make check
# FIXME: fix dependencies and re-enable this
