#!/usr/bin/python

import os
import sys
import gnome


def main(args):
    if len(args) < 1:
        raise Exception, "Missing sound file as argument."

    gnome.sound_init("localhost")
    sound_file = os.path.join(args[0])
    gnome.sound_play(sound_file)

    device = "None"
    path = "/proc/asound/card0/id"
    if os.path.exists(path):
        fd = file(path, "r")
        device = fd.readline().strip()

    print device


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
