#!/bin/sh

address=$1
file=$2

hciconfig hci0 reset

echo "Searching for FTP service."
sdptool search FTP > ~/result.tmp

channel=`sdptool search FTP | grep -A 10 '$address' | grep 'Channel' | awk '{print $2}')`
echo $channel $address

obexftp -b $address -B $channel -p $file
