#!/usr/bin/python

import sys
import dbus
from subprocess import call


def main():
    # Connect to the session
    bus = dbus.SessionBus()

    unity = bus.get_object("org.freedesktop.DBus", "/com/canonical/Unity")
    if unity.NameHasOwner("com.canonical.Unity"):
        retcode = call(["/usr/lib/unity/autopilot.py"])
        return retcode
    else:
        print "Unity is not running"
        return 1

if __name__ == "__main__":
    sys.exit(main())
