#!/bin/bash

# Any active connections?
conn=''

active_connection=$(nmcli -f SSID,ACTIVE dev wifi list | grep yes)
if [ $? -eq 0 ]
then
    ap=$(echo $active_connection | awk -F\' '{print $2}')
    conn=$(nmcli -f NAME con list | grep $ap)
else
    conn=$(nmcli -f NAME,TYPE con list | grep wireless | head -n 1 | awk '{print $1}')
fi

echo $conn

# Find out if wireless is enabled
nmcli nm wifi | grep -q 'enabled'
if [ $? -ne 0 ]
then
    # Find out why
    rfkill list wifi | grep 'Hard blocked' | grep -q yes
    if [ $? -eq 0 ]
    then
        blkmessage='Your wireless may be hardware blocked. You may need
                    to use your wireless key/switch to re-enable it.'
        echo $blkmessage
    fi
fi

# Check if there's a connection already (wireless or otherwise)
nmcli dev status | grep -q '\<connected\>'
if [ $? -eq 0 ]
then
    # Disconnect, pause for a short time
    for iface in `nmcli -f GENERAL dev list | grep 'GENERAL.DEVICE' | awk '{print $2}'`
    do
        nmcli dev disconnect iface $iface
    done
    sleep 2
fi

nmcli con up id $conn
