#!/bin/bash

# Any active connections?
conn=''

active_connection=$(nmcli -f SSID,ACTIVE dev wifi list | grep yes)
if [ $? -eq 0 ]
then
    ap=$(echo $active_connection | awk -F\' '{print $2}')
    conn=$(nmcli -f NAME con list | grep $ap)
else
    conn=$(nmcli -f NAME,TYPE con list | grep wireless | head -n 1 | awk '{print $1}')
fi

echo $conn

# Find out if wireless is enabled
nmcli nm wifi | grep -q 'enabled'
if [ $? -ne 0 ]
then
    # Find out why
    rfkill list wifi | grep 'Hard blocked' | grep -q yes
    if [ $? -eq 0 ]
    then
        blkmessage='Your wireless may be hardware blocked. You may need
                    to use your wireless key/switch to re-enable it.'
        echo $blkmessage
    fi
fi

# Regardless, still try and enable it - can't do any harm
nmcli nm wifi on

# Check if there's a connection already
nmcli dev status | grep wlan | grep -q '\<connected\>'
if [ $? -eq 0 ]
then
    # Disconnect, pause for a short time
    nmcli dev disconnect iface $(nmcli -f GENERAL dev list | grep -B 1 'wireless' | grep 'GENERAL.DEVICE' | awk '{print $2}')
    sleep 2
fi

nmcli con up id $conn
