#!/usr/bin/python
#
# This file is part of Checkbox.
#
# Copyright 2011 Canonical Ltd.
#
# Checkbox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Checkbox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Checkbox.  If not, see <http://www.gnu.org/licenses/>.
#
import sys
import posixpath

from checkbox.parsers.cpuinfo import (
    CpuinfoParser,
    CpuinfoResult,
    )

# Filename where cpuinfo is stored.
CPUINFO_FILENAME = "/proc/cpuinfo"

# Filename where maximum frequency is stored.
FREQUENCY_FILENAME = "/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq"


class ResourceResult(CpuinfoResult):

    def __setitem__(self, key, value):
        print "%s: %s" % (key, value)

    def setSpeed(self, speed):
        # Check for frequency scaling
        if posixpath.exists(FREQUENCY_FILENAME):
            speed = open(FREQUENCY_FILENAME).read().strip()
            speed = int(speed) / 1000

        self["speed"] = speed


def main():
    stream = open(CPUINFO_FILENAME)
    parser = CpuinfoParser(stream)

    result = ResourceResult()
    parser.run(result)

    return 0


if __name__ == "__main__":
    sys.exit(main())
