#!/usr/bin/env python

import sys
import os
import time

from subprocess import Popen, PIPE
from uuid import uuid4
from optparse import OptionParser

CONNECTIONS_PATH='/etc/NetworkManager/system-connections/'

def connection_section(ssid, uuid):
    
    if not uuid: uuid = uuid4()

    connection = """
[connection]
id=%s
uuid=%s
type=802-11-wireless
    """ % (ssid, uuid)

    # Get MAC address
    nmcli_proc = Popen("nmcli -f GENERAL dev list | grep 802-11-wireless -A 2 | awk '/HWADDR/ {print $2}'",
                       shell=True, stdout=PIPE, stderr=PIPE)
    (stdout, stderr) = nmcli_proc.communicate()

    wireless = """
[802-11-wireless]
ssid=%s
mode=infrastructure
mac-address=%s
    """ % (ssid, stdout.strip())

    return connection + wireless

def security_section(security, key):
    # Need to add security field to 802-11-wireless section
    wireless_security = """
security=802-11-wireless-security

[802-11-wireless-security]
    """

    if security.lower() == 'wpa':
        wireless_security += """
key-mgmt=wpa-psk
auth-alg=open
psk=%s
        """ % key

    elif security.lower() == 'wep':
        wireless_security += """
key-mgmt=none
wep-key=%s
        """ % key

    return wireless_security

def ip_sections():
    ip = """
[ipv4]
method=auto

[ipv6]
method=auto
    """

    return ip

def block_until_created(connection, block_for):
    
    while block_for > 0:
        nmcli_con = Popen(['nmcli','con','up','id', connection], stdout=PIPE)
        (stdout, stderr) = nmcli_con.communicate()

        if 'state: activated' in stdout:
            break

        time.sleep(2)
        block_for = block_for - 2
        print("Trying for %d more seconds..." % block_for)

def main():
    parser = OptionParser()
    
    parser.add_option('-S', '--security',
                      help="""The type of security to be used by the connection.
                              One of wpa and wep. No security will be used if
                              nothing is specified.""")
    parser.add_option('-K', '--key',
                      help="The encryption key required by the router.")
    parser.add_option('-U', '--uuid',
                      help="""The uuid to assign to the connection for use by
                            NetworkManager. One will be generated if not
                            specified here.""")
    parser.add_option('-B', '--block-for',
                      help="""The length of time to block the scripts exit
                              for until the connection is created.""",
                      default=10)

    (options, args) = parser.parse_args()

    if len(args) < 1:
        print("Must specify an SSID to connect to.")
        sys.exit(1)
    
    connection_info = connection_section(args[0], options.uuid)

    if options.security:
        # Set security options
        if not options.key:
            print "You need to specify a key using --key if using wireless security."
            sys.exit(1)

        connection_info += security_section(options.security, options.key)
    elif options.key:
        print "You specified an encryption key but did not give a security type using --security."
        sys.exit(1)
    
    connection_info += ip_sections()
        
    try:
        connection_file = open(CONNECTIONS_PATH + args[0], 'w')
        connection_file.write(connection_info)
        os.fchmod(connection_file.fileno(), 0600)
        connection_file.close()
    except IOError:
        print "Can't write to " + CONNECTIONS_PATH + args[0] + ". Is this command being run as root?"
        sys.exit(1)

    block_until_created(args[0], options.block_for)

if __name__ == "__main__":
    main()
