#!/usr/bin/env python

from gi.repository import Gtk,Gdk

class Application:
    def __init__(self):
        self.colors = iter(["red", "green", "blue", "white", "black"])
        self.window = Gtk.Window(Gtk.WindowType.TOPLEVEL)
        self.window.set_decorated(False)
        self.window.fullscreen()
        self.window.modify_bg(Gtk.StateType.NORMAL,
                              Gdk.color_parse(self.colors.next()))

        self.window.connect("key-press-event", self.rotate_bg_color)
        self.window.add_events(Gdk.EventMask.BUTTON_PRESS_MASK)
        self.window.connect("button-press-event", self.rotate_bg_color)

        self.window.show()

    def rotate_bg_color(self, window, event):
        try:
            self.window.modify_bg(Gtk.StateType.NORMAL,
                                  Gdk.color_parse(self.colors.next()))
        except StopIteration:
            Gtk.main_quit()

    def main(self):
        Gtk.main()

if __name__ == "__main__":
    app = Application()
    app.main()
