#!/usr/bin/python

import re
import sys

from subprocess import Popen, PIPE
from xml.dom.minidom import parseString


def main(args):
    xml = Popen("lshw -xml -C system -C disk", shell=True,
        stdout=PIPE, stderr=PIPE).communicate()[0]

    # Safely encode assuming latin1
    xml = unicode(xml, "latin1")
    xml = re.sub(ur"[^\x09\x0a\x0d\x20-\ud7ff\ue000-\ufffd]", "", xml,
        re.UNICODE)

    # Safely reencode using utf8
    xml = xml.encode("utf8")
    dom = parseString(xml)
    nodes = [n for n in dom.getElementsByTagName("node")
        if n.getAttribute("id") in ("disk", "storage")]
    if nodes:
        for node in nodes:
            details = []
            for name in ["product", "description"]:
                if node.getElementsByTagName(name):
                    detail = node.getElementsByTagName(name)[0].firstChild.data
                    details.append(detail)

            print " ".join(details)
    else:
        print "None."

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
