#!/usr/bin/python
import sys
from subprocess import Popen, PIPE

def main():
    output = Popen('hdparm -tT /dev/sda',
                   stdout=PIPE, shell=True).communicate()[0]

    for line in output.splitlines()[-2:]:
        line = line.lstrip()
        line = ("%s %s"
                % (line[:line.find(':')],
                   line[line.rfind('='):]))
        print line


if __name__ == "__main__":
    sys.exit(main())
