#!/usr/bin/python

import os
import sys

from subprocess import Popen, PIPE


def main(args):
    directory = os.path.dirname(__file__)
    script = os.path.join(directory, "device_list")
    disk_devices_string = Popen([script, "disk"], stdout=PIPE).communicate()[0]

    disk_devices = disk_devices_string.strip().split("\n")
    if not disk_devices:
        print "None"

    for disk_device in disk_devices:
        disk = os.path.basename(disk_device)
        model_path = "/sys/block/%s/device/model" % disk
        model_file = open(model_path)
        try:
            model_name = model_file.read().strip()
            print model_name
        finally:
            model_file.close()

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
