#!/usr/bin/env python3

import sys
from argparse import ArgumentParser
from subprocess import Popen, PIPE

TESTS = ['acpiinfo',
         'acpitables',
         'apicedge',
         'apicinstance',
         'bios_info',
         'bios32',
         'checksum',
         'crs',
         'dmesg_common',
         'dmi_decode',
         'ebda',
         'fadt',
         'fan',
         'hda_audio',
         'hpet_check',
         'maxfreq',
         'maxreadreq',
         'mcfg',
         'microcode',
         'mtrr',
         'nx',
         'os2gap',
         'osilinux',
         'smbios',
         'version',
         'virt',
         'wmi',
         'cstates',
         'dmar']


def main():
    parser = ArgumentParser(description='Tests the system BIOS using the \
                            Firmware Test Suite')
    group = parser.add_mutually_exclusive_group()
    group.add_argument('-c', '--cpufreq',
                      action='store_true',
                      help=('Chose this option to run '
                            'the CPU Frequency Scaling test only'))
    group.add_argument('-w', '--wakealarm',
                      action='store_true',
                      help='Run the fwts wakealarm test only')
    parser.add_argument('-a', '--all',
                      action='store_true',
                      help='Run ALL FWTS automated tests (assumes -w and -c)')
    parser.add_argument('-l', '--log',
                      default='/tmp/fwts_results.log',
                      help=('Specify the location and name of the log file. '
                            '[Default: %(default)s]'))
    args = parser.parse_args()

    tests = []
    results = {}
    if args.cpufreq:
        tests += ['cpufreq']
    elif args.wakealarm:
        tests += ['wakealarm']
    elif args.all:
        tests += ['wakealarm', 'cpufreq'] + TESTS
    else:
        tests += TESTS

    # run the tests we want
    for test in tests:
        command = ('fwts -q --stdout-summary -r %s %s'
                   % (args.log, test))
        results[test] = (Popen(command, stdout=PIPE, shell=True)
                         .communicate()[0].strip()).decode()

    # parse the summaries
    passed = 0
    failed_critical = 0
    failed_high = 0
    failed_medium = 0
    failed_low = 0

    for test in tests:
        if results[test] == 'FAILED_CRITICAL':
            failed_critical += 1
        elif results[test] == 'FAILED_HIGH':
            failed_high += 1
        elif results[test] == 'FAILED_MEDIUM':
            failed_medium += 1
        elif results[test] == 'FAILED_LOW':
            failed_low += 1
        elif results[test] == 'PASSED':
            passed += 1
        else:
            continue

    print("Critical Failures: %d" % failed_critical)
    print("High Failures: %d" % failed_high)
    print("Medium Failures: %d" % failed_medium)
    print("Low Failures: %d" % failed_low)
    print("Passed: %d" % passed)

    if failed_critical != 0 or failed_high != 0:
        return 1
    else:
        return 0

if __name__ == '__main__':
    sys.exit(main())
