#!/usr/bin/python3

import sys
import time
from gi.repository import Gst
from argparse import ArgumentParser


def main():
    parser = ArgumentParser(description = 'Simple GStreamer pipeline player')
    parser.add_argument('PIPELINE',
        help='Quoted GStreamer pipeline to launch')
    parser.add_argument('-t', '--timeout',
        type=int, required=True,
        help='Timeout for running the pipeline')
    args = parser.parse_args()

    Gst.init(None)
    element = Gst.parse_launch(args.PIPELINE)
    element.set_state(Gst.State.PLAYING)

    if args.timeout:
        time.sleep(args.timeout)
        
    element.set_state(Gst.State.NULL)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
