#!/usr/bin/python
#
# This file is part of Checkbox.
#
# Copyright 2009 Canonical Ltd.
#
# Checkbox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Checkbox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Checkbox.  If not, see <http://www.gnu.org/licenses/>.
#
import re
import sys


# Filename where meminfo is stored.
FILENAME = "/proc/meminfo"


def get_meminfo():
    key_value_pattern = re.compile(r"(?P<key>.*):\s+(?P<value>.*)")
    meminfo_map = {
        "MemTotal": "total",
        "SwapTotal": "swap"}

    meminfo = {}
    file = open(FILENAME, "r")
    for line in file.readlines():
        line = line.strip()
        match = key_value_pattern.match(line)
        if match:
            key = match.group("key")
            if key in meminfo_map:
                key = meminfo_map[key]
                value = match.group("value")
                (integer, factor) = value.split()
                meminfo[key] = integer * 1024

    return meminfo

def main():
    meminfo = get_meminfo()
    for key, value in meminfo.iteritems():
        print "%s: %s" % (key, value)

    return 0


if __name__ == "__main__":
    sys.exit(main())
