#! /bin/sh

#assume that the test fail at the beginning
found=0

iw_inter=`iwconfig 2>/dev/null | grep "^[^ ]" | awk '{print $1}'`
if [ -z "$iw_inter" ]; then
    echo "No wireless device found"
    exit 0
fi
for dev in $iw_inter ; do
    iw_net=`iwlist $dev scan 2>/dev/null | grep "ESSID:"`
    if [ ! -z "$iw_net" ] ; then
        echo "Wireless network found on "$dev
        cat << EOF
$iw_net
EOF
        found=`expr $found + 1`
    else
        echo "No wireless network found on "$dev
    fi
done
if [ $found -eq 0 ]; then
    exit 1
fi
