#!/usr/bin/python

import os
import sys

from xml.dom.minidom import parseString


def main(args):
    command = "lshw -xml 2>/dev/null"
    xml = os.popen(command).read()
    dom = parseString(xml)
    nodes = [n for n in dom.getElementsByTagName("node")
        if n.getAttribute("class") == "network" and n.getAttribute("handle")]
    if nodes:
        for node in nodes:
            print node.getElementsByTagName("vendor")[0].firstChild.data, \
                  node.getElementsByTagName("product")[0].firstChild.data
    else:
        print "Not found."

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
