#!/usr/bin/python
"""
Check that it's possible to establish http and ftp connections against
ubuntu.com
"""
import urllib2
import sys


def check_url(url):
    """
    Open URL and return True if no exceptions were raised
    """
    try:
        urllib2.urlopen(url)
    except urllib2.URLError:
        return False

    return True

def main():
    """
    Check HTTP and FTP connections
    """
    url = {"http": "http://cdimage.ubuntu.com/daily/current/",
           "ftp": "ftp://cdimage.ubuntu.com/cdimage/daily/current/",}

    results = {}
    for protocol, value in url.iteritems():
        results[protocol] = check_url(value)
    
    if all(results.itervalues()):
        return 0
    else:
        return 1

if __name__ == "__main__":
    sys.exit(main())
