#!/usr/bin/env python3

import os
import re
from glob import glob


def device_removable(d):
    """
    Follow pmount policy to find removable devices
    """
    with open('/sys/block/%s/device/block/%s/removable' % (d, d)) as f:
        if f.read(1) == '1':
            return 'removable'

    rootdir_pattern = re.compile('^.*?/devices')
    path = rootdir_pattern.sub('', os.readlink('/sys/block/%s' % d))
    hotplug_buses = ("usb", "ieee1394", "mmc", "pcmcia", "firewire")
    for bus in hotplug_buses:
        if os.path.exists('/sys/bus/%s' % bus):
            for device_bus in os.listdir('/sys/bus/%s/devices' % bus):
                device_link = rootdir_pattern.sub('', os.readlink(
                    '/sys/bus/%s/devices/%s' % (bus, device_bus)))
                if re.search(device_link, path):
                    return 'removable'

    return 'internal'


devices = [re.sub('.*/(.*?)/device', '\g<1>', d)
    for d in glob('/sys/block/*/device')]

for d in devices:
    print('%s: %s' % (d, device_removable(d)))
