#!/usr/bin/env python3

import os
import re
from glob import glob


def device_removable(d):
    """
    Follow pmount policy to find removable devices
    """

    removable_property = 'internal'
    rootdir_pattern = re.compile('^.*?/devices')
    with open('/sys/block/%s/device/block/%s/removable' % (d, d)) as f:
        removable_property = f.read(1)

    if removable_property == '1':
        return 'removable'
    else:
        removable_property = 'internal'

    path = rootdir_pattern.sub('', os.readlink('/sys/block/%s' % d))
    hotplug_buses = ("usb", "ieee1394", "mmc", "pcmcia", "firewire")
    for bus in hotplug_buses:
        if not os.path.exists('/sys/bus/%s' % bus):
            continue
        for device_bus in os.listdir('/sys/bus/%s/devices' % bus):
            device_link = rootdir_pattern.sub('', os.readlink(
                '/sys/bus/%s/devices/%s' % (bus, device_bus)))
            if re.search(device_link, path):
                return 'removable'

    return removable_property


devices = [re.sub('.*/(.*?)/device', '\g<1>', d)
    for d in glob('/sys/block/*/device')]

for d in devices:
    print('%s: %s' % (d, device_removable(d)))
