#!/usr/bin/python

import os


ati_brain_damage = []
command = 'xrandr -q'
for item in os.popen('lsmod | grep fglrx'):
    ati_brain_damage.append(item)

if len(ati_brain_damage):
    resolution = "impossible with fglrx"
else:
    resolution = None
    res, freq = None, None
    contents = os.popen(command).read()
    for line in contents.splitlines():
        line = line.strip()
        if line.endswith("*"):
            # gutsy
            fields = line.replace("*", "").split()
            if len(fields) == 2:
                res, freq = fields
            else:
                res, freq = fields[0], "N/A"
            break
        elif line.startswith("*"):
            # dapper
            fields = line.replace("*", "").split('  ')
            res = fields[1].replace(" ", "")
            if len(fields) < 4:
                freq = "N/A"
            else:
                freq = fields[4]
            break

    if res:
        resolution = "%s @ %d Hz" % (res, float(freq))
    else:
        resolution = "Not detected."

print resolution
