#!/bin/bash

IFS=$','
result=0

if [ -z "$SOURCES_LIST" ]; then
    echo "sources_list not set to location of sources list file in checkbox.ini"
    exit 1
fi

if [ -z "$REPOSITORIES" ]; then
    echo "repositories not set to list of expected repositories in checkbox.ini"
    exit 1
fi

for repository in $REPOSITORIES; do
    if grep -q "$repository" "$SOURCES_LIST"; then
        echo "$repository found in $SOURCES_LIST"
    else
        echo "$repository not found in $SOURCES_LIST"
        result=1
    fi
done

exit $result
