#!/bin/bash
#
# Simplistic test to determine whether the system successfully resumed
# from suspend and thawed from hibernate.

if zgrep -q '/usr/lib/pm-utils/sleep.d/000kernel-change resume suspend: success.' /var/log/pm-suspend.log*; then
    suspend_status="pass"
else
    suspend_status="untested"
fi

if zgrep -q '/usr/lib/pm-utils/sleep.d/000kernel-change thaw hibernate: success.' /var/log/pm-suspend.log*; then
    hibernate_status="pass"
else
    hibernate_status="untested"
fi

cat <<EOF
plugin: shell
name: sru/suspend
status: $suspend_status
description: SRU suspend test.

plugin: shell
name: sru/hibernate
status: $hibernate_status
description: SRU hibernate test.

EOF
