#!/usr/bin/env python3

import sys
import re
import argparse
from io import StringIO
from subprocess import Popen, PIPE, check_output, STDOUT, CalledProcessError
from checkbox.parsers.udevadm import UdevadmParser

# Command to retrieve udev information.
COMMAND = 'udevadm info --export-db'


class TouchResult:

    attributes = {}

    def addDevice(self, device):
        if getattr(device, 'category') == 'TOUCH':
            self.attributes['product'] = getattr(device, 'product')


def get_touch_attributes():
    output, err = Popen(COMMAND, stdout=PIPE, shell=True).communicate()
    if err:
        print("Error running $s" % ' '.join(COMMAND))
        print(err)
        return None
        
    udev = UdevadmParser(StringIO(output.decode("unicode-escape")))

    result = TouchResult()
    udev.run(result)

    return result.attributes['product']

def can_scroll(touchpad):
    COMMAND = "xinput list '%s'" % touchpad
    horizontal_supported = ""
    vertical_supported = ""
    bl = re.compile("Button labels")
    vert_up = re.compile(".*Button Wheel Up.*")
    vert_down = re.compile(".*Button Wheel Down.*")
    horiz_left = re.compile(".*Button Horiz Wheel Left.*")
    horiz_right = re.compile(".*Button Horiz Wheel Right.*")
    proc = Popen(COMMAND, stdout=PIPE, shell=True, universal_newlines=True)
    output = proc.stdout.read()
    if bl.findall(output):
        if vert_up.search(output) and vert_down.search(output):
            vertical_supported = "supported"
        else:
            print("Vertical scroll not found")
            vertical_supported = "unsupported"
        if horiz_left.search(output) and horiz_right.search(output):
            horizontal_supported = "supported"
        else:
            print("Horizontal scroll not found")
            horizontal_supported = "unsupported"
    else:
        print("Button label capabilities not found")
        return False
    return horizontal_supported, vertical_supported



def main():
    product = get_touch_attributes()
    if product:
        print("device_name: %s" % product)
    else:
        print("No Touchpad Detected")
    horiz,vert = can_scroll(product)
    print("horizontal_scroll: %s" % horiz)
    print("vertical_scroll: %s" % vert)


if __name__ == "__main__":
    main()