#!/usr/bin/python3
#
# This file is part of Checkbox.
#
# Copyright 2011 Canonical Ltd.
#
# Checkbox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Checkbox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Checkbox.  If not, see <http://www.gnu.org/licenses/>.
#
import os
import sys

from checkbox.parsers.udevadm import UdevadmParser


# Command to retrieve udev information.
COMMAND = "udevadm info --export-db"


class UdevResult:

    attributes = ("path", "bus", "category", "driver", "product_id",
        "vendor_id", "subproduct_id", "subvendor_id", "product", "vendor",)

    def addDevice(self, device):
        for attribute in self.attributes:
            value = getattr(device, attribute)
            if value is not None:
                print("%s: %s" % (attribute, value))

        print()


def main():
    stream = os.popen(COMMAND)
    udev = UdevadmParser(stream)

    result = UdevResult()
    udev.run(result)

    return 0


if __name__ == "__main__":
    sys.exit(main())
