#!/bin/bash
# A short script to determine if the test machine will
# funtion properly as a Compute Node in an OpenStack 
# environment.

# First, let's see if we have processor flags
virt=$(egrep -m1 -w '^flags[[:blank:]]*:' /proc/cpuinfo | egrep -wo '(vmx|svm)')
[ "$virt" == "vmx" ] && brand="Intel"
[ "$virt" == "svm" ] && brand="AMD"
if [ -z "$virt" ]; then
    echo "INFO: Virtualization Flags not found" && exit 1
else
    echo "INFO: Virtualization flag $virt indicates $brand processor"
fi

# Now let's do some math
mem_total=0
for size in `dmidecode -t 17 | grep Size | grep -vi "No module" |awk '{print $2}'`
do
    mem_total=$(echo $mem_total + $size |bc)
done

if [ $mem_total -ge 4096 ]; then
    echo "INFO: System has at least 4096MB, enough for a small Compute Node"
    exit 0
else
    echo "INFO: System does not have enough RAM to successfully function as a Compute Node"
    exit 1
fi
