#!/usr/bin/env python3
# This file is part of Checkbox.
#
# Copyright 2014 Canonical Ltd.
# Written by:
#  Maciej Kisielewski <maciej.kisielewski@canonical.com>
#
# Checkbox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.

#
# Checkbox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Checkbox.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import json
import subprocess
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('job', help="Qml file of the job to run")
    args = parser.parse_args()

    test_result_object_prefix = "qml: __test_result_object:"
    test_res = None
    p = subprocess.Popen(['qmlscene', '--job', args.job, 'qml_shell.qml'],
                         stderr=subprocess.PIPE)
    for line in iter(p.stderr.readline, ''):
        line = line.decode(sys.stderr.encoding)
        if not line:
            break
        if line.startswith(test_result_object_prefix):
            obj_json = line[len(test_result_object_prefix):]
            test_res = json.loads(obj_json)
        else:
            print(line)

    if not test_res:
        return "Job did not return any result"

    print("Test outcome: {}".format(test_res['outcome']))
    return test_res['outcome'] != "pass"

if __name__ == "__main__":
    sys.exit(main())
